# Needed to launch the image
variables:
  USER_ID: "$(id -u)"
  GROUP_ID: "$(id -g)"

stages:
  - test
  - build

before_script:
  - yarn install --frozen-lockfile --cache-folder .yarn
  - yarn ng --version

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .yarn

lint:
  stage: test
  image: node:alpine
  tags: [docker]
  script:
    - yarn lint
  allow_failure: true

test:
  stage: test
  image: esanzgar/node-chromium
  tags: [docker]
  script:
    - yarn test:sr:chromium
  artifacts:
    paths:
      - coverage/

docs:
  stage: test
  image: node:alpine
  tags: [docker]
  script:
    - yarn docs
  artifacts:
    paths:
      - docs/

build:
  stage: build
  image: node:alpine
  tags: [docker]
  script:
    - yarn packagr
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths:
      - dist-lib/
  only:
    - master
