# Needed to launch the image
variables:
  USER_ID: "$(id -u)"
  GROUP_ID: "$(id -g)"

stages:
  - test
  - build

before_script:
  - yarn install --frozen-lockfile --cache-folder .yarn
  - yarn ng --version

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .yarn

lint:
  stage: test
  image: node:10.15.0-alpine
  # image: node:alpine # replace when node-sass@4.9.4 compiles on the latest
  tags: [docker]
  script:
    - yarn lint
  allow_failure: true

test:
  stage: test
  image: esanzgar/node-chromium:10-node-chromium
  # image: esanzgar/node-chromium
  tags: [docker]
  script:
    - yarn test:sr:chromium
  artifacts:
    paths:
      - coverage/

pages:
  stage: test
  image: node:10.15.0-alpine
  # image: node:alpine # replace when node-sass@4.9.4 compiles on the latest
  tags: [docker]
  script:
    - yarn docs
    - mkdir public
    - cp -r docs/* public/
  artifacts:
    paths:
      - public

build:
  stage: build
  image: node:10.15.0-alpine
  # image: node:alpine # replace when node-sass@4.9.4 compiles on the latest
  tags: [docker]
  script:
    - yarn packagr
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths:
      - dist-lib/
  only:
    - master
